# Generated by Django 5.2.4 on 2025-09-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolium', '0003_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('category', models.CharField(choices=[('app', 'App'), ('product', 'Product'), ('branding', 'Branding'), ('books', 'Books')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
