# Generated by Django 5.2.4 on 2025-09-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolium', '0004_portfolio_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='created_at',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('app', 'App'), ('product', 'Product'), ('web', 'Web')], max_length=50),
        ),
    ]
