# Generated by Django 5.2.4 on 2025-09-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolium', '0005_remove_portfolio_created_at_portfolio_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('app', 'App'), ('branding', 'Branding'), ('product', 'Product'), ('web', 'Web')], max_length=50),
        ),
    ]
