# Generated by Django 5.2.4 on 2025-09-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolium', '0006_alter_portfolio_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('app', 'App'), ('branding', 'Branding'), ('product', 'Product'), ('book', 'Book'), ('web', 'Web')], max_length=50),
        ),
    ]
