# Generated by Django 5.2.4 on 2025-09-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolium', '0007_alter_portfolio_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('map_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
