# Generated by Django 5.2.4 on 2025-09-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolium', '0008_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='No subject', max_length=200),
        ),
    ]
